### ISSUE TITLE
Darkly SCSS

### ISSUE THREAD

**Issue by cprudhoe** [roelmann/moodle-theme_waxed#11]
The preset Darkly top header (I think you call it Navbar) has a white background.
The language selection drop list, messages icon, and social icons are also white.
The only way to see these items is to hover over their location.
Please tell me how to change the background color or adjust the text colors so these items are visible.
I would edit the Darkly preset, but I can't identify which CSS code controls the top header.

You can see the problem on the front page at https://www.musapp.club.  On the top header, float your mouse over the area just to the right of "Learn to Sing or Play Music".  You will see the language drop list.

Thanks
Clarence Prudhoe
cprudhoe@musapp.com

**Comment by cprudhoe** [comment]
Also, in the Darkly preset, the Add an Activity popup has the same background color as does the text.  You cant read the Activity names.
Please tell me what SCSS code to use to adjust the text color or the background color.
Thanks,
Clarence Prudhoe
cprudhoe@musapp.com

**Comment by roelmann** [comment]
Hi Clarence, Can you please confirm that you are definitely using Waxed with the Darkly preset and no other alterations and customisations.
When I apply Darkly on Waxed, I get a grey navbar with darker grey messaging and notifications icons (while the social icons in Waxed are actually in the footer anyway - and in Darkly have white icons in a blue box with the footer having a very dark grey background.
Anyway, you can change the navbar background by setting .bg-faded {background-color:#000;} in the customscss setting box (#000 will make it black, you can change that according to your needs)
The Add an Activity pop up also has darker grey (#888) text against a light grey background. So it does sound as if you may have edited some of the scss, or added some customscss (such as changing the body colour) as this does not come across in the same way as the default Darkly preset.
If you need to make changes, the best way is to use tools such as the built in developer tools in Chrome or Firefox to find the appropriate css selector and then make those changes in the customscss setting in Waxed.

**Comment by cprudhoe** [comment]
Hi Richard, thanks for your work on this theme.
I am using the newest Waxed theme on Moodle 3.4+ with the "Darkly" presets and I found and issue that I need your help with.

When you make an entry on the calendar, the event description doesn't show when you click on the event date.  I assume you should be able to see the event description.

Thanks for your help.
Clarence

**Comment by roelmann** [comment]
Superceded by new version with new BS4 bootswatch presets
