### ISSUE TITLE
Social Media Icons are not shown on Moodle 3.5

### ISSUE THREAD

**Issue by sbourget** [roelmann/moodle-theme_waxed#12]
For some reason, the social media icons are being displayed as white text on a white background.  (See attached screenshot)

![social-icon-waxed](https://user-images.githubusercontent.com/1093550/40318732-9b80da56-5cf3-11e8-9da0-8176e049f4c3.JPG)

I'm using the following CSS to work around the issue at the moment:
.socials .fa-stack {color:#3497D1}
Waxed version 3.5.1.0

**Comment by roelmann** [comment]
With which preset? Waxed includes all the bootswatch presets, so this could be an upstream issue with one of them

**Comment by sbourget** [comment]
I was using the default preset, with no custom CSS
![waxed-settings](https://user-images.githubusercontent.com/1093550/40366567-6f9f8c86-5da5-11e8-9c92-0ff450bde8d2.JPG)

**Comment by sbourget** [comment]
Also reproduce able with yeti, Lumen, and Flaty (Did not try the other presets)
