### ISSUE TITLE
Course summary images not working

### ISSUE THREAD

**Issue by sbourget** [roelmann/moodle-theme_waxed#13]
When you add an image to the course summary file area it no longer displays in the page header.  

This is due to a typo (the closing curly brace should be a closing parenthesis) in the template here:
https://github.com/roelmann/moodle-theme_waxed/blob/master/templates/header.mustache#L25

The line:

`<div class='withimage' style='background-image:url("{{{image}}}"};background-size:100% 100%'>`

should be

`<div class='withimage' style='background-image:url("{{{image}}}");background-size:100% 100%'>`

**Comment by sbourget** [comment]
Also, the lines: (https://github.com/roelmann/moodle-theme_waxed/blob/master/templates/header.mustache#L24-L26)
`{{#image}}`
`<div class='withimage' style='background-image:url("{{{image}}}"};background-size:100% 100%'>`
`{{/image}} `
Need to be moved before the line: (https://github.com/roelmann/moodle-theme_waxed/blob/master/templates/header.mustache#L23)
`<div class="card-body">`
Otherwise the image is distorted and both header images (the site wide one and the course image) are displayed

**Comment by roelmann** [comment]
Thank you for these reports I will get them fixed asap and pushed out.
Hopefully tonight or tomorrow
