### ISSUE TITLE
Gear menu when editing a block is overlapped by the surrounding blocks

### ISSUE THREAD

**Issue by sbourget** [roelmann/moodle-theme_waxed#2]
On the front page, when you have editing on, and try to edit a block  The contextual menu is obscured by the block underneath.  See the attached image.
![z-index-waxed](https://cloud.githubusercontent.com/assets/1093550/22108326/980c2dd8-de20-11e6-9a9c-16959637f978.PNG)

(It's almost like the z-index for the menu is incorrect)

**Comment by gjb2048** [comment]
Hi Richard,

Saw the issue.  Seen before elsewhere.  'opacity' attribute issue.  So start investigation there.

G

**Comment by roelmann** [comment]
Thanks Gareth - yes same, have come across this before and have a 'cure' for it somewhere. That was on a BS3 theme though so hadn't ported the fix across to waxed. Will also need to investigate if this is a core issue with Boost.

**Comment by sbourget** [comment]
Thanks,
Looks like my Custom CSS was causing the issue.

I had applied the following CSS to waxed:
body {background: no-repeat center center fixed}
#region-main {opacity: 0.90}
aside.block {opacity: 0.90}

It looks like my issue was caused by the aside.block rule above. 
If it's fixable in waxed then great, otherwise feel free to close as "not a bug"

**Comment by roelmann** [comment]
Ah - thank you. Was just going to ask which preset or if custom css as the default or any of the ones I normally use don't have it :)

I think when I have come across this previously, it was only the menu itself that had been given an opacity and I got around it by removing that opacity on hover. But as opacity applies to all child selectors too, you would have to have the block itself lose its opacity on hover/click, not just the menu.
