### ISSUE TITLE
Low contrast with the default preset

### ISSUE THREAD

**Issue by mudrd8mz** [roelmann/moodle-theme_waxed#5]
With freshly installed theme and no customisation, the default preset leads to some suboptimal low contrast at some places - notably at filepicker icons:

![image](https://cloud.githubusercontent.com/assets/85831/22527741/940386d6-e8d0-11e6-8249-3ab995fb161c.png)

**Comment by mudrd8mz** [comment]
I understand this is hard to guarantee with all provided presets (those come from bootswatch right?). My reasoning is just that the "default" preset should look good. I found Cerulean ok with regards to this, for example.

**Comment by roelmann** [comment]
default preset is also a standard bootswatch preset (flatly). Agree though that others look better - going to swap default to be Cerulean copy, which is one I've used before as a base for themes. Looks clean enough to be a default, but adds a bit of colour/style to look better than the outright plain one.

**Comment by roelmann** [comment]
Done
