### ISSUE TITLE
Install on 3.2.1+ caused 500 errors. Could be a peculiarity of my build.

### ISSUE THREAD

**Issue by AlexW9** [roelmann/moodle-theme_waxed#8]
Thanks for all the work on waxed so far, looks really promising.

I tried installing this theme both by dropping it into the theme directory (Moodle 3.2.1+ VM) and also via the plugin however in both cases (despite install itself being successful) it caused site to 500. I managed to revert site by manually accessing server/admin/plugins.php?theme=clean and uninstalling (hadn't managed to even switch to Waxed in theme selector yet either!).
Had thought could be bad interaction with cleanurls plugin however uninstalled that and tried re install but same result.

I cant see anyone else having a similar issue so could be a peculiarity of my install?

Thanks,

Alex

Checked apache error logs but lots of noise, a few things could be relevant:
`[Tue Feb 07 15:43:01.110990 2017] [core:error] [pid 18836:tid 140352694454016] [client IP:19132] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://server/course/view.php?id=183`

**Comment by roelmann** [comment]
Hi Alex, I've now installed it on several different machines on a few different sites as well as about 6 different development moodles over 2 laptops. I know others have installed it including David who did the plugin review. I haven't had any other reports of issues installing it.
Are you able to turn Moodle error messages on to see if there's anything more useful than the Apache ones (eg the stack trace it provides).

**Comment by roelmann** [comment]
Can't replicate awaiting more info

**Comment by AlexW9** [comment]
Richard,
Thanks for getting back to me.
I tried downloading a fresh vanilla Moodle 3.2 (xampp version) and installing the Waxed theme on there which worked fine. I did some more debugging on the original VM and seems some legacy fiddling I'd done was causing a core_renderer error overriding region_main_settings_menu() . 
`[Thu Feb 09 15:10:05.248073 2017] [proxy_fcgi:error] [pid 18834:tid 140352786773760] [client IP:1455] AH01071: Got error 'PHP message: PHP Fatal error:  Call to undefined method theme_boostw_core_renderer::region_main_settings_menu() in /var/www/html/theme/boost/layout/columns2.php on line 42\n', referer: http://server/login/index.php`
When I removed the core_renderer.php from that (unrelated work) everything worked fine so obviously the Waxed theme just happened to trigger that pre existing underlying issue. Please feel free to close the ticket. 
Thanks,
Alex

**Comment by roelmann** [comment]
Thanks for the feedback Alex - good to know you found the issue
